version: "3.8"
services:
#  frontend:
#    build: .
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

  backend:
    image: node:18
    working_dir: /server
    volumes:
      - ./db.json:/server/db.json
    command: npx json-server --watch db.json --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
